services:
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   container_name: nginx
  #   networks:
  #     - nginx-network
  #   ports:
  #     - "8080:80"
  blog-app:
    container_name: blog-app
    build:
      context: .
      dockerfile: ./Dockerfile.app
    # command: bash -c "cd /blog-app; python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py collectstatic --no-input && python3 manage.py runserver 0.0.0.0:8000"
    networks:
      - django-network
    ports:
      - "8000:80"
    env_file:
      - blog-app.env
    hostname: "blog-app.com"
networks:
  django-network:
    driver: bridge