services:
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   container_name: nginx
  #   networks:
  #     - nginx-network
  #   ports:
  #     - "8080:80"
  blog-project:
    build:
      context: .
      dockerfile: ./Dockerfile.app
    networks:
      - nginx-network
    ports:
      - "8000:80"
    env_file:
      - ./.env

networks:
  nginx-network:
    driver: bridge